version: '2'
services:
  sam-postgres-db:
    image: postgres
    container_name: sam-postgres-db
    environment:
      - POSTGRES_PASSWORD=XvvnYrUd5b20
    ports:
      - '5432:5432'
    networks:
      pillreminder:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  pillreminder:
